#ifndef _HMD_DBUS_PATH_H
#define _HMD_DBUS_PATH_H
#include "hmd/hmdpub.h"

#define HMD_DBUS_BUSNAME        "aw.hmd"
#define HMD_DBUS_OBJPATH        "/aw/hmd"
#define HMD_DBUS_INTERFACE      "aw.hmd"

#define HMD_DBUS_CONF_METHOD_LOCAL_HANSI                             "config_local_hansi"
#define HMD_DBUS_METHOD_DELETE_LOCAL_HANSI                           "delete_local_hansi"
#define HMD_DBUS_CONF_METHOD_REMOTE_HANSI_STATE_CHANGE               "remote_hansi_state_change"
#define HMD_DBUS_CONF_METHOD_DHCP_AUTO_RESTART                       "auto_dhcp_restart"
#define HMD_DBUS_CONF_METHOD_REMOTE_HANSI                            "config_remote_hansi"
#define HMD_DBUS_METHOD_SET_LOCAL_HANSI_STATE                        "set_local_hansi_state"
#define HMD_DBUS_METHOD_SET_LOCAL_HANSI_UPLINK_IF                    "set_local_hansi_uplink_if"
#define HMD_DBUS_METHOD_SET_LOCAL_HANSI_DOWNLINK_IF                  "set_local_hansi_downlink_if"
#define HMD_DBUS_METHOD_DELETE_SLOTID_IMG                            "delete_slotid_img"
#define HMD_DBUS_METHOD_SET_LOCAL_HANSI_DISABLE_ENABLE               "set_local_hansi_enable_disable"
#define HMD_DBUS_METHOD_SHOW_HMD_INFO                                "show_hmd_info"
#define HMD_DBUS_METHOD_SET_LOCAL_HANSI_GATEWAY_IF                   "set_local_hansi_gateway_if"
#define HMD_DBUS_METHOD_HAD_NOTIFY_HMD_STATE                         "had_notify_hmd_state"
#define HMD_DBUS_METHOD_WID_NOTIFY_HMD_UPDATE_STATE                  "wid_notify_hmd_state"
#define HMD_DBUS_METHOD_ASD_NOTIFY_HMD_UPDATE_STATE                  "asd_notify_hmd_state"
#define HMD_DBUS_HAD_GET_ALIVE_SLOT_NO                               "had_get_alive_slot_no"
#define HMD_DBUS_METHOD_DELETE_REMOTE_HANSI                          "delete_remote_hansi"
#define HMD_DBUS_METHOD_SHOW_RUNNING                                 "hmd_show_running_config"
#define HMD_DBUS_METHOD_HANSI_SHOW_RUNNING                           "hmd_hansi_show_running_config"
#define HMD_DBUS_CONF_METHOD_LICENSE_ASSIGN                          "assign_license"
#define HMD_DBUS_CONF_METHOD_LICENSE_ASSIGN_SHOW                     "assign_license_show"
#define HMD_DBUS_METHOD_LICENSE_SHOW_RUNNING                         "hmd_license_show_running_config"
#define HMD_DBUS_METHOD_SET_HANSI_CHECK_STATE                        "set_hansi_check_state"
#define HMD_DBUS_CONF_METHOD_SERVICE_TFTP_SWITCH                     "service_tftp_switch"
#define HMD_DBUS_CONF_METHOD_SHOW_SERVICE_TFTP_SWITCH                "show_service_tftp"
#define HMD_DBUS_CONF_METHOD_SERVICE_FTP_SWITCH                      "service_ftp_switch"
#define HMD_DBUS_CONF_METHOD_SHOW_SERVICE_FTP_SWITCH                 "show_service_ftp"
#define HMD_DBUS_CONF_METHOD_SET_FAST_FORWARDING                     "set_fast_forwarding"
#define HMD_DBUS_CONF_METHOD_SET_TUNNEL_QOS_MAP                      "set_tunnel_qos_map"
#define HMD_DBUS_CONF_METHOD_SET_TUNNEL_MM                          "set_tunnel_mm"
#define HMD_DBUS_CONF_METHOD_SET_IPFRAG_INGRESS_PMTU                 "set_ipfrag_ingress_pmtu"
#define HMD_DBUS_CONF_METHOD_SET_IPFRAG_INFORM_NHMTU_INSTEAD         "set_ipfrag_inform_nhmtu_instead"
#define HMD_DBUS_CONF_METHOD_SET_IPFRAG_IGNOREDF                     "set_ipfrag_ignoredf"
#define HMD_DBUS_CONF_METHOD_SHOW_AP_IMG_FILES                       "show_ap_img_files"
#define HMD_DBUS_CONF_METHOD_SHOW_HMD_BAK_FOREVER_INFO               "show_hmd_bak_forever_info"
#define HMD_DBUS_CONF_METHOD_SET_WID_CLEAR_BINDING_INTERFACE_FLAG    "set_wid_clear_binding_interface_flag"
#define HMD_DBUS_CONF_METHOD_SET_VRRP_BAKUP_FOREVER                  "set_vrrp_bakup_forever"
#define HMD_DBUS_METHOD_DELETE_LOCAL_HANSI_LINK_IF                   "delete_link_ifname"
#define HMD_DBUS_CONF_METHOD_FEMTO_SERVICE_SWITCH                    "femto_service_switch"
#define HMD_DBUS_CONF_METHOD_FEMTO_SERVICE_CHECK                     "femto_service_state_check"  
#define HMD_DBUS_METHOD_SET_HMD_TIMER_CONFIG_SAVE_STATE              "set_hmd_timer_config_save_state"    /*fengwenchao add 20130412 for hmd timer config save*/
#define HMD_DBUS_METHOD_SET_HMD_TIMER_CONFIG_SAVE_TIMER              "set_hmd_timer_config_save_timer"    /*fengwenchao add 20130412 for hmd timer config save*/
#endif

