#ifndef _WID_DBUS_DEF1_H
#define _WID_DBUS_DEF1_H
#include "wcpss/waw.h"

extern char WID_DBUS_BUSNAME[PATH_LEN];
extern char WID_DBUS_OBJPATH[PATH_LEN];
extern char WID_DBUS_INTERFACE[PATH_LEN];
/*extern char WID_DBUS_SUCCESS 0
extern char WID_DBUS_ERROR	1
extern char WID_DBUS_NO_WLAN_ID	2
extern char WID_DBUS_NO_WTP_ID	3
extern char WID_DBUS_NO_Radios_ID	4
extern char WLAN_ID_BE_USED	5
extern char WLAN_ID_NOT_EXIST	6
extern char WTP_ID_BE_USED	7
extern char WTP_ID_NOT_EXIST	8
*/

enum wid_dbus_result_no_e
{
	WID_DBUS_SUCCESS = 0,
	WID_DBUS_ERROR = 1, /* general use, no detail error information*/ 
	SYSTEM_CMD_ERROR = 2,
	UNKNOWN_ERROR = 3,
	MALLOC_ERROR = 4,
	PARAM_NULL_POINTER = 5,

	WLAN_ID_BE_USED = 6,
	WLAN_ID_NOT_EXIST = 7,
	WLAN_ID_LARGE_THAN_MAX = 8,
	WLAN_APPLY_SECURITY_FIRST = 9,
	SECURITYINDEX_IS_SAME = 10,			//fengwenchao add 20110110
	
	WLAN_NOT_BINDING_IF = 11,	
	Wlan_IF_NOT_BE_BINDED = 12,
	WLAN_BE_ENABLE = 13,	
	WLAN_BE_DISABLE = 14,
	WLAN_NOT_NEED_NAS = 15,
	
	WLAN_CREATE_BR_FAIL = 16,
	WLAN_DELETE_BR_FAIL = 17,
	WLAN_CREATE_L3_INTERFACE_FAIL = 18,
	WLAN_DELETE_L3_INTERFACE_FAIL = 19,
	WID_BINDING_WLAN = 20,

	WLAN_NOT_BINDING_VLAN = 21,	
	WLAN_BINDING_VLAN = 22,
	WLAN_SERVICE_CONTROL_BE_USED = 23,	
	WLAN_UPLINK_ALREADY = 24,	
	WLAN_UPLINK_IS_ENABLE = 25,
	
	WLAN_IF_NOT_BE_TUNNELMODE = 26,
	RAOMING_DISABLE_FIRST = 27,		
	ISOLATION_CONFLICT = 28,
	WDS_MODE_BE_USED = 29,
	WTP_ID_BE_USED = 30,
	
	WTP_ID_NOT_EXIST = 31,
	WTP_ID_LARGE_THAN_MAX = 32,
	WTP_OVER_MAX_NUM = 33,	
	WTP_MAC_BE_USED = 34,	
	WTP_SN_BE_USED = 35,
	
	WTP_BE_USING = 36,
	WTP_IS_NOT_BINDING_WLAN_ID = 37,
	WTP_CLEAR_BINDING_WLAN_SUCCESS = 38,
	WTP_WLAN_BINDING_NOT_MATCH = 39,	
	WTP_IF_NOT_BE_BINDED = 40,
	
	WTP_NOT_IN_RUN_STATE = 41,	
	WTP_NO_SURPORT_TYPE = 42,
	WTP_NO_SURPORT_Rate = 43,
	WTP_LESS_THAN_STATIC_WTP = 44,	
	WTP_OVER_MAX_BSS_NUM = 45,
	
	WTP_WEP_NUM_OVER = 46,
	WTP_NO_NEIGHBORAP = 47,
	WID_NO_SURPORT_MODEL = 48,
	WTP_NO_SURPORT_CHANNEL = 49,	
	WID_AP_NO_STATICS = 50,
	
	NO_WTP_IN_RUN_STATE = 51,
	WID_AP_SCANNING_DISABLE = 52,
	WID_WTP_LOCATION_NOT_SET = 53,
	MODEL_NO_EXIST = 54,	
	MODEL_NO_CONFIG = 55,
	
	SUPPORT_VERSION_NOT_EXIST = 56,	
	VERSION_NOT_SUPPORTED = 57,
	SAMPLE_THROUGHPUT_NOT_ENABLE = 58,		
	WID_NO_WHITELIST = 59,		
	WID_NO_BLACKLIST = 60,
	
	WID_TRANSMIT_POWER_CONTROL_DISABLE = 61,
	AP_L2_ISOLATION_ENABLE_OR_DIS_ALREADY = 62,		//xiaodawei add for ap l2 isolation enable or disable already, 20101207	
	MODEL_BIND_EVER = 63,						//mahz add for ap upgrade	
	MODEL_BIND_NEVER = 64,	
	UPDATE_CONFIG_FAIL = 65,
	
	UPDATE_PROCESS = 66,
	NO_WIDS_DEVICE = 67,		
	AUTO_AP_LOGIN_INTERFACE_ERROR = 68,
	AUTO_AP_LOGIN_INTERFACE_NOT_SET = 69,	
	AUTO_AP_LOGIN_WLAN_NOT_SET = 70,
	
	AUTO_AP_LOGIN_SWITCH_IS_DISABLE = 71,
	AUTO_AP_LOGIN_SWITCH_HAS_ALREADY_SETTED = 72,
	RADIO_ID_BE_USED = 73,
	RADIO_ID_NOT_EXIST = 74,	
	RADIO_ID_LARGE_THAN_MAX = 75,
	
	RADIO_NO_BINDING_WLAN = 76,
	RADIO_IS_DISABLE = 77,
	RADIO_NOT_SUPPORT_COMMAND = 78,
	RADIO_SUPPORT_RATE_EMPTY = 79,	
	RADIO_SUPPORT_RATE_ONE = 80,
	
	RADIO_SUPPORT_RATE_EXIST = 81,
	RADIO_SUPPORT_RATE_NOT_EXIST = 82,	
	RADIO_SUPPORT_RATE_CONFLICT = 83,
	RADIO_SUPPORT_MAX_RATE_NOT_ONE = 84,	
	RADIO_MODE_IS_11N = 85,
	
	RADIO_MODE_IS_PURE_N = 86,
	RADIO_ENCRYPTION_NO_MATCH = 87,	
	RADIO_BRMAC_NOT_EXIST = 88,	
	RADIO_SECTOR_DISABLE = 89,
	RADIO_AMPDU_DISABLE = 90,
	
	RADIO_11N_AMPDU_MUTEX = 91,
	RADIO_11N_AMSDU_MUTEX = 92,
	RADIO_CHANNEL_OFFSET_NEED_BE_RESET = 93,
	RADIO_HT_IS_NOT_40 = 94,	
	RADIO_IN_EBR = 95,						//fengwenchao add for radio whether in ebr check
	
	RADIO_CHAINMASK_NUM_1 = 96,
	RADIO_CHAINMASK_NUM_2 = 97,
	RADIO_CHAINMASK_NUM_3 = 98,
	MCS_CROSS_THE_BORDER = 99,
	MAC_MPDU_MSDU_MODE = 100,
	
	RADIO_NO_BINDING_WQOS = 101,
	RADIO_SERVICE_CONTROL_BE_USED = 102,	
	TXPOWER_OVER_TW = 103,	
	TXPOWER_OVER_TW_THREE = 104,	
	TXPOWEROFF_LARGER_THAN_MAX = 105,			//xiaodawei add, txpoweroffset*step > max_txpower
	
	RADIO_SET_TXPOF_COUNTRY_CODE_ERROR = 106,
	CHECK_CHANNEL_CWMODE_FAIL = 107,	
	CHECK_COUNTRY_CODE_FAIL = 108,
	BSS_ID_LARGE_THAN_MAX = 109,
	BSS_NOT_EXIST = 110,
	
	BSS_NOT_ENABLE = 111,
	BSS_BE_ENABLE = 112,
	BSS_IF_NEED_CREATE = 113,	
	BSS_IF_NEED_DELETE = 114,
	BSS_CREATE_L3_INTERFACE_FAIL = 115,
	
	BSS_DELETE_L3_INTERFACE_FAIL = 116,
	BSS_L3_INTERFACE_ADD_BR_FAIL = 117,	
	BSS_L3_INTERFACE_DEL_BR_FAIL = 118,
	SET_MAX_STANUM_SMALLER_THAN_CURRENT_STANUM = 119,
	NO_SURPPORT_IPIP = 120,
	
	PAST_L3_INTERFACE_ERROE = 121,
	APPLY_IF_FAIL = 122,
	L3_INTERFACE_ERROR = 123,
	ETH_NOT_EXIST = 124,	
	WID_EBR_IF_NOEXIT = 125,
	
	BINDING_IPV6_ADDRE_RROR = 126,		
	INTERFACE_NOT_BE_BINDED = 127,
	INTERFACE_NOT_EXIST = 128,	
	INTERFACE_HAVE_NO_IP_ADDR = 129,
	WID_ADD_RADIO_IF_FAIL = 130,
	
	INTERFACE_NOT_L3_IF = 131,
	IF_BINDING_FLAG = 132,
	IF_POLICY_CONFLICT = 133,		
	MORE_THAN_ONE_IF = 134,	
	IF_HAS_BEEN_LISTENNING = 135,
	
	NO_IF_HAS_THIS_IP = 136,
	WID_INTERFACE_NOT_BE_LOCAL_BOARD = 137,
	WID_QOS_BE_USED = 138,	
	WID_QOS_NOT_EXIST = 139,	
	WID_QOS_RADIO_SHOULD_BE_DISABLE = 140,
	
	WID_QOS_WMM_MAP_DISABLE = 141,	
	WID_QOS_STREAM_ERROR = 142,
	WID_QOS_PARAMETER_ERROR = 143,	
	WID_QOS_PARAMETER_VALUE_ERROR = 144,	
	WID_QOS_BE_USED_BY_RADIO = 145,
	
	WID_EBR_ERROR = 146,
	WID_EBR_BE_USED = 147,	
	WID_EBR_NOT_EXIST = 148,	
	WID_EBR_SHOULD_BE_DISABLE = 149,	
	WID_EBR_IFLIST_EMPTY = 150,
	
	SWITCH_IS_DISABLE = 151,	
	SWITCH_HAS_ALREADY_SETTED = 152,
	AC_IP_EXIST = 153,	
	AC_IP_NOT_EXIST = 154,	
	AC_IP_BIND_IF_EXIST = 155,
	
	AC_BALANCE_STATE = 156,
	AC_BALANCE_FLOW = 157,	
	AC_BALANCE_NUM = 158,	
	WID_NEED_REBOOT = 159,	
	GROUP_ID_EXIST = 160,
	
	GROUP_ID_NOT_EXIST = 161,
	GROUP_ID_OVER_MAX = 162,
	INVALID_LICENSE_TYPE = 163,
	WRONG_LICENSE_LIST = 164,
	LICENSE_NUM_LARGER_THAN_MAX = 165,
	
	LICENSE_NUM_LESS_THAN_TWO = 166,
	LICENSE_NOT_EXIST = 167,	
	LICENSE_TYPE_DUPLICATED = 168,
	LICENSE_TYPE_BINDED = 169,
	LICENSE_NO_BINDING_SUCCESS = 170,
	
	LICENSE_NOT_BINDED = 171,
	LICENSE_BINDED_ANOTHER = 172,	
	CURRENT_NUM_MORE_THAN_MAX = 173,
	FLOW_CHECK_BE_DISABLE = 174,	
	ACCOUNT_AFTER_AUTHORIZE = 175,
	
	WID_MAC_ADD_ALREADY = 176,
	WID_UPGRADE_NUM_OVERFLOW = 177,	
	MAC_DOESNOT_EXIT = 178,	
	MAC_ALREADY_EXIT = 179,	
	ESSID_IS_EXIST = 180,
	
	ESSID_NOT_EXIST = 181,
	ESSID_LIST_IS_NULL = 182,
	WID_STATE_BE_SAME = 183,	
	WID_ADD_BLACK_WHITE_OUI_MAC_ERR = 184,
	WID_DEL_BLACK_WHITE_OUI_MAC_ERR = 185,
	
	INVALID_TYPE = 186,
	WID_UNKNOWN_ID = 187,	
	WID_ILLEGAL_INPUT = 188,	
	VALUE_OUT_OF_RANGE = 189,	
	MIN_LARGER_THAN_MAX = 190,
	
	VALUE_IS_NONEED_TO_CHANGE = 191,/*used to mark value is the same to the command,so no need to be changed*/
	MAC_GROUP_EXIST = 192,	
	MAC_GROUP_NOT_EXIST = 193,
	MAC_IN_LIST = 194,
	MAC_NOT_IN_LIST = 195,
	
	RADIO_NO_BINDING_MACGROUP = 196,
	GROUP_ID_LARGE_THAN_MAX = 197,	
	MACGRP_IS_BINDED = 198,	
	WTP_BIND_MACGRP = 199,
	WLAN_BIND_MACGRP = 200,
	
	MAC_LIST_IS_FULL = 201,
	WLAN_CTR_LIST_ENABLE = 202, /*ENR-17*/
	RADIO_SA_IS_ENABLE = 203,
	RADIO_SA_PARA_INVALID = 204,
	UPGRADE_IS_WORKING = 205,

	/*****for dynamic vlan added and others**************/					
	VLAN_GROUP_ID_LARGE_THAN_MAX = 206,
	VLAN_GROUP_SERVICE_ENABLE = 207,	
	VLAN_GROUP_SERVICE_DISABLE = 208,
	GROUP_MEMBER_OVER_MAX_NUM = 209,
	RADIO_ID_NOT_IN_VLANGRP = 210,
	
	VLAN_ID_NOT_EXIST = 211,	
	NO_SET_VLANGRP_WLAN = 212,
	NO_SET_VLANGRP_VLAN = 213,
	BSS_IN_OTHER_VLANGRP = 214,
	DYNAMIC_VLAN_NOT_DISABLE  = 215,
	
	DYNAMIC_VLAN_PARAMTER_ERROR = 216,	
	DYNAMIC_VLAN_DELETE_ERROR = 217,
	DYNAMIC_VLAN_ADD_ERROR = 218,

	WID_PARA_RANGE_INVALID = 219,	
	NO_SET_GROUP_RADIO_MEMBER = 220,
	FAILED_GET_REPLY = 221,
	WID_QOS_DEFAULT = 222,
	WTP_NO_ROGUEAP = 223,
	MAC_IN_ROGUE_WHITELIST = 224,	
	MAC_IN_ROGUE_BLACKLIST = 225,
	
	WID_AP_SCANNING_COUNTERMEASURES_DISABLE = 226,
	RADIO_MODE_IS_NOT_11AC = 227,

	WID_SERVER_IP_ERROR = 228,
	WID_SERVER_PORT_ERROR = 229,
	WID_USER_VLANID_ERROR = 230,
	WID_SSID_ERROR = 231, 
	WID_SECURITY_WEP_KEY_ERROR = 232,
	WID_SECURITY_WPA_KEY_ERROR = 233,
	WID_SECURITY_KEY_ERROR = 234,

	WLAN_ID_ERROR = 235,
	WTP_IN_OFFLINE_STATE = 236,
	/******************end***************************/
};

enum wid_radio_type {
	IEEE80211_11B = 0x1,
	IEEE80211_11A = 0x2,
	IEEE80211_11G = 0x4,
	IEEE80211_11N = 0x8,
	IEEE80211_11AN = 0x10,      //fengwenchao add for GM 20111109
	IEEE80211_11GN = 0x20,      //fengwenchao add for GM 20111109
	IEEE80211_11AC = 0x40,
};

enum wid_check_type {
	WID_WTP_CHECK,
	WID_WLAN_CHECK,
	WID_RADIO_CHECK,
	WID_SECURITY_CHECK,

};


/*
 arg lists for method WID_DBUS_CONF_METHOD_SHOWWLAN
  in arg list:
	BYTE WlanID //ID of WLAN which is unique sign of wlan
  out arg list:  // in the order as they are appended in the dbus message.
	STRING 	WLANNAME//name of wlan
	BYTE 	WLANID//ID of WLAN which is unique sign of wlan
	STRING 	ESSID//essid of wlan
	BYTE	AAW//aute add wtp 0(disable)/1(default enable)
	BYTE	STATUS//WLAN Status 0(default disable)/1(enable)
	BYTE	VID//num of vlan which wlan in
	BYTE	Wlan_Index
*/
extern char WID_DBUS_CONF_METHOD_SHOWWLAN[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOWWLAN_OF_ALL[PATH_LEN];    //fengwenchao add 20101223
extern char WID_DBUS_CONF_METHOD_WLANLIST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WTPLIST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WTPLIST_BYMAC[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WTPLIST_NEW[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOWWTP_BYMODEL[PATH_LEN];    //fengwenchao add 20110226
extern char WID_DBUS_CONF_METHOD_SHOWWTP_BYVERSION[PATH_LEN];  //fengwenchao add 20110314
extern char WID_DBUS_CONF_METHOD_WTPLIST_NEW_BYINTERFACE[PATH_LEN];		//xiaodawei add, 20110301
extern char WID_DBUS_CONF_METHOD_WTPLIST_UPDATE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AC_ACCESS_WTPLIST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_CLEAN_AC_ACCESS_WTPLIST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_OLD_AP_IMG[PATH_LEN];


extern char WID_DBUS_CONF_METHOD_ACVERSION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_ECHOTIMER[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_WTP_RUNNING_CONFIG[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_WLAN_SHOW_RUNNING_CONFIG_START[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WLAN_BALANCE_RSSI[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_APPAY_WLAN_BALANCE_TRIGER[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_WLAN_SHOW_RUNNING_CONFIG_END[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_WTP_SHOW_RUNNING_CONFIG_START[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_WTP_SHOW_RUNNING_CONFIG_END[PATH_LEN];
/*
 arg lists for method WID_DBUS_CONF_METHOD_WLAN
  in arg list:
	BYTE WlanID //ID of WLAN which is unique sign of wlan
  out arg list:  // in the order as they are appended in the dbus message.
	UNIT32	ret//success or fail(reason)
*/
extern char WID_DBUS_CONF_METHOD_WLAN[PATH_LEN];

/*
 arg lists for method WID_DBUS_CONF_METHOD_SHOWWTP
  in arg list:
	BYTE WTPID //ID of WTP which is unique sign of wtp
  out arg list:  // in the order as they are appended in the dbus message.
	STRING 	WTPNAME//name of wtp
	BYTE 	WTPID//ID of wtp which is unique sign of wtp
	UNIT32	WTPSN//sn of wtp
	UNIT32	WTPMOD//model of wtp
	STRING	WTPIP//ip of wtp
	STRING	WTPMAC//mac of wtp
	BYTE	CTR_ID//id of control tunnel
	BYTE	DTA_ID//id of data tunnel
*/
extern char	WID_DBUS_CONF_METHOD_SHOWWTP[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_CONFIG_WTP[PATH_LEN];  //fengwenchao add 20101223

extern char	WID_DBUS_WTP_METHOD_SHOW_WTP_MODEL_CODE_VERSION[PATH_LEN];


/*
 arg lists for method WID_DBUS_CONF_METHOD_WTP
  in arg list:
	BYTE WTPID //ID of WLAN which is unique sign of wlan
  out arg list:  // in the order as they are appended in the dbus message.
	UNIT32	ret//success or fail(reason)
*/
extern char WID_DBUS_CONF_METHOD_WTP[PATH_LEN];


/*
 arg lists for method WID_DBUS_CONF_METHOD_SHOWRADIO
  in arg list:
	BYTE Radio_G_ID //global ID of radio which is unique sign of radio
  out arg list:  // in the order as they are appended in the dbus message.
	BYTE	WTPID
	BYTE	Radio_G_ID
	BYTE	Radio_L_ID
	UNIT32	Radio_TYPE//type of Radio(a/b/g/n)
	BYTE	Radio_Chan//channel of radio
	UNIT16	Radio_TXP//tx power of radio
	BYTE	AdStat//state of admin
	BYTE	OpStat//state of operate
*/
extern char	WID_DBUS_CONF_METHOD_SHOWRADIO[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_RADIOLIST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_RADIO[PATH_LEN];

/*
 arg lists for method WID_DBUS_CONF_METHOD_ADD_DEL_WLAN
  in arg list:
	BYTE	isADD //determine ADD(1) or DEL(0)	
  	STRING  WLANNAME//name of wlan
  	BYTE	  WLANID//ID of WLAN which is unique sign of wlan
  	STRING  ESSID//essid of wlan
  out arg list:  // in the order as they are appended in the dbus message.
	UNIT32	ret//success or fail(reason)
*/
extern char	WID_DBUS_CONF_METHOD_ADD_DEL_WLAN[PATH_LEN];
extern char	WID_DBUS_CONF_METHOD_ADD_DEL_WLAN_CN[PATH_LEN];

/*
 arg lists for method WID_DBUS_CONF_METHOD_ADD_DEL_WTP
  in arg list:
	BYTE	isADD //determine ADD(1) or DEL(0)	
	STRING 	WTPNAME//name of wtp
	BYTE 	WTPID//ID of wtp which is unique sign of wtp
	UNIT32	WTPSN//sn of wtp
	UNIT32	WTPMOD//model of wtp
  out arg list:  // in the order as they are appended in the dbus message.
	UNIT32	ret//success or fail(reason)
*/
extern char	WID_DBUS_CONF_METHOD_ADD_DEL_WTP[PATH_LEN];

extern char	WID_DBUS_CONF_METHOD_ADD_DEL_WTP_BY_MAC[PATH_LEN];


extern char WID_DBUS_CONF_METHOD_UPDATE_WTP_COUNT[PATH_LEN];
	
extern char	WID_DBUS_WLAN_OBJPATH[PATH_LEN];
extern char WID_DBUS_WLAN_INTERFACE[PATH_LEN];


/*
arg lists for method WID_DBUS_CONF_METHOD_WLAN_ENABLE
 in arg list:
   	BYTE	WlanID//id of wlan which you want enable or disable
  	BYTE	DisWLAN //determine disable(1) or enable(0)WLAN  
out arg list:  // in the order as they are appended in the dbus message.
	UNIT32	ret//success or fail(reason)
*/
extern char WID_DBUS_WLAN_METHOD_ENABLE[PATH_LEN];
extern char WID_DBUS_WDS_METHOD_ENABLE[PATH_LEN];


/*
arg lists for method WID_DBUS_CONF_METHOD_WLAN_APPLY_IF
 in arg list:
   	BYTE	WlanID//id of wlan which you want enable or disable
  	STRING	interface//which interface wlan apply  
out arg list:  // in the order as they are appended in the dbus message.
	UNIT32	ret//success or fail(reason)
*/
extern char WID_DBUS_WLAN_METHOD_APPLY_IF[PATH_LEN];

extern char WID_DBUS_WTP_METHOD_APPAY_WTP_IFNAME[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_APPAY_WTP_MAX_STA[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_APPAY_WTP_TRIGER[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_APPAY_WTP_FLOW_TRIGER[PATH_LEN];
extern char WID_DBUS_WTP_INTERFACE_CHECK_WTP_STA[PATH_LEN];

extern char WID_DBUS_WLAN_METHOD_FLOW_CHECK[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_NO_FLOW_TIME[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_LIMIT_MIN_FLOW[PATH_LEN];

extern char WID_DBUS_WTP_METHOD_LAN_VLAN[PATH_LEN];

extern char WID_DBUS_WTP_METHOD_SET_UPGRADE_MODE[PATH_LEN];

extern char WID_DBUS_WTP_METHOD_APPAY_WTP_WLANID[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_APPAY_WLAN_IFNAME[PATH_LEN];

extern char WID_DBUS_WLAN_METHOD_APPAY_WLAN_MAX_STA[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_WLAN_MAX_STA_NEW[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_WLAN_L2_ISOLATION[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_WLAN_STA_STATIC_ARP[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_WLAN_ACCESS_STA_LIMIT_RSSI[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_APPAY_WLAN_BALANCE_PARA[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_APPAY_WLAN_FLOW_BALANCE_PARA[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_SET_SILENCE_PERIOD[PATH_LEN];

extern char WID_DBUS_WLAN_METHOD_APPAY_WLAN_BALANCE_SWITCH[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_WTP_USED[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_DELETE_WLAN_ID[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_DISABLE_WLAN_ID[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_ENABLE_WLAN_ID[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SHOW_WLAN_ID[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_VERSION_PATH[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_CONFIG_PORT_ENABLE[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_CONFIG_PORT[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTPNAME[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTPSN[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_STANAME[PATH_LEN];
extern char WID_DEBUS_WLAN_METHOD_SET_EAP_MAC[PATH_LEN];

extern char WID_DBUS_WTP_METHOD_ARCHIVE_ALERT[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_ARCHIVE_ALERTLIST[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_GET_WTP_ALERTIDS[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_GET_COUNTRY_CODE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_IP_NETWORK[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_COVER_RADIO_WLAN[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_RECORD_AP_UPDATE_STATUS[PATH_LEN];

extern char WID_DBUS_WTP_METHOD_SET_WTP_TERMINAL_DISTRUB_INFOMATION_SWITCH[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_TERMINAL_DISTRUB_INFOMATION_PKT[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_TERMINAL_DISTRUB_INFOMATION_STA_NUM[PATH_LEN];

extern char WID_DBUS_METHOD_SET_AP_HEART_STATISTICS_SWITCH[PATH_LEN];
extern char WID_DBUS_METHOD_SET_AP_HEART_STATISTICS_COLLECT_TIME[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_EXTENSION_INFOMATION_SWITCH[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_EXTENSION_INFOMATION_REPORTINTERVAL[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_USERNAME_PASSWORD[PATH_LEN] ;
extern char WID_DBUS_WTP_METHOD_SET_WTP_STA_DEAUTH_MESSAGE_REPORT_SWITCH[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_STA_ALL_FLOW_INFORMATION_REPORT_SWITCH[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_STA_INFOMATION_SWITCH[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_STA_INFOMATION_REPORTINTERVAL[PATH_LEN];

extern char WID_DBUS_WTP_METHOD_SET_WTP_CHECK_WLANID[PATH_LEN];

extern char WID_DBUS_WTP_METHOD_SET_WTP_WIDS_INTERVAL[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_WIDS_THRESHOLD[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_WIDS_LASTTIME_IN_BLACK[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_AC_MASTER_BAK_CORRECT_WTP_STATE_TIMER[PATH_LEN]; //fengwenchao add 20120117 for onlinebug-96
extern char WID_DBUS_WTP_METHOD_SET_WTP_IF_INFO_SWITCH[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_AC_ACTIVE_BAK_STATE[PATH_LEN];

extern char WID_DBUS_WTP_METHOD_SET_WTP_WIDS_SET[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SHOW_WTP_WIDS_SET[PATH_LEN];

extern char WID_DBUS_WTP_METHOD_SET_WTP_IF_INFO_REPORTINTERVAL[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_INTERFACE_UPDOWN[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_INTERFACE_ETH_RATE[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SHOW_WTP_IF_INFO[PATH_LEN];

extern char WID_DBUS_WTP_METHOD_SET_WTP_NTPCLIENT[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_UPDATE_WTP_CONFIG[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_REBOOT[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_REBOOT_ALL[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_REBOOT_BY_WLANID[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_REBOOT_BY_INTERFACE[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_REBOOT_BY_MODEL[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_REBOOT_BY_LIST[PATH_LEN];

extern char WID_DBUS_WTP_METHOD_GET_WTP_BSS_PKT_INFO[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SHOW_WTP_BSS_PKT_INFO[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SHOW_WTP_RADIO_PKT_INFO[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SHOW_WTP_RADIO_PKT_INFO_TUNNEL[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SHOW_WTP_ETH_PKT_INFO[PATH_LEN];

extern char WID_DBUS_WTP_METHOD_SHOW_WTP_WIFI_SNR_INFO[PATH_LEN];

extern char WID_DBUS_WTP_METHOD_SET_PORT_VLAN_SECURITY[PATH_LEN];  /*sz20080827*/
extern char WID_DBUS_WTP_METHOD_SET_PORT_VLAN_ENABLE[PATH_LEN];  /*sz20080827*/
extern char WID_DBUS_WTP_METHOD_SET_SECURITY[PATH_LEN]; /*sz20080827*/
extern char WID_DBUS_WTP_METHOD_SET_VLAN_LIST_ENABLE[PATH_LEN];  /*sz20080827*/
extern char WID_DBUS_WTP_METHOD_DELETE_AP_MODEL[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_AP_TIMER[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_AP_CHECKTIMER[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_AP_COLLECT_TIME[PATH_LEN];	/*nl 2010/07/13*/
extern char WID_DBUS_WLAN_METHOD_DELETE_IF[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_SHOW_IF[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_HIDE_ESSID[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_L3IF_POLICY[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_L3IF_POLICY2[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_SET_NAS_IDENTIFIER[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_REMOVE_NAS_IDENTIFIER[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_ROAMING_POLICY[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_SET_BRIDGE_ISOLATION[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_SET_BRIDGE_MULTICAST_ISOLATION[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_SHOW_BRIDGE_ISOLATION[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_SET_BRIDGE_SAMEPORTSWICTH[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_SET_ESSID[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_SET_ASCII_ESSID[PATH_LEN];     /*fengwenchao add 20110307*/
extern char WID_DBUS_WLAN_METHOD_WHOLE_WLAN_TRAFFIC_LIMIT_VALUE[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_WHOLE_WLAN_SEND_TRAFFIC_LIMIT_VALUE[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_SET_PACKET_POWER[PATH_LEN];

extern char WID_DBUS_WLAN_METHOD_WHOLE_WLAN_STA_AVERAGE_TRAFFIC_LIMIT_VALUE[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_WHOLE_WLAN_STA_AVERAGE_SEND_TRAFFIC_LIMIT_VALUE[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_WHOLE_WLAN_BSS_MULTI_USER_OPTIMIZE_SWITCH[PATH_LEN];
extern char  WID_DBUS_RADIO_METHOD_MOLTI_USER_OPTIMIZE_SWITH [PATH_LEN];


extern char WID_DBUS_WLAN_METHOD_UNDO_WLAN_VLANID[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_SET_WLAN_VLANID[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_SET_NAS_PORT_ID[PATH_LEN];			//mahz add 2011.5.25
extern char  WID_DBUS_WLAN_METHOD_SET_WLAN_HOTSPOTID[PATH_LEN];		
extern char  WID_DBUS_WLAN_METHOD_CLEAN_WLAN_HOTSPOTID[PATH_LEN];		
extern char WID_DBUS_WLAN_METHOD_SET_TUNNEL_WLAN_VLAN[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_SHOW_TUNNEL_WLAN_VLAN[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_SET_WLAN_VLAN_PRIORITY[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_SHOW_WLAN_VLAN_INFO[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_L3IF_POLICY_BR[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_L3IF_POLICY2_BR[PATH_LEN];

/*added end 20080701*/

extern char WID_DBUS_WTP_OBJPATH[PATH_LEN];
extern char WID_DBUS_WTP_INTERFACE[PATH_LEN];



extern char	WID_DBUS_RADIO_OBJPATH[PATH_LEN];
extern char WID_DBUS_RADIO_INTERFACE[PATH_LEN];

/*
arg lists for method WID_DBUS_CONF_METHOD_RADIO_STXP
 in arg list:
   	BYTE	Radio_G_ID//Global id of Radio
	UNIT16	Radio_TXP//tx power of radio
out arg list:  // in the order as they are appended in the dbus message.
	UNIT32	ret//success or fail(reason)
*/
extern char WID_DBUS_RADIO_METHOD_SET_TXP[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_TXPOF[PATH_LEN];

/*
arg lists for method WID_DBUS_CONF_METHOD_RADIO_SCHAN
 in arg list:
   	BYTE	Radio_G_ID//Global id of Radio
	BYTE	Radio_Chan//channel of radio
out arg list:  // in the order as they are appended in the dbus message.
	UNIT32	ret//success or fail(reason)
*/
extern char WID_DBUS_RADIO_METHOD_DYNAMIC_SELECT_CHAN[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_CHAN[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_RATE[PATH_LEN];
extern char WID_DBUG_RADIO_METHOD_SET_11N_RATE_PARAS[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_MODE[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_FRAGMENTATION[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_BEACON[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_RTSTHROLD[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_DTIM[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_STATUS[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_WDS_STATUS[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_PREAMBLE[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_LONGRETRY[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_SHORTRETRY[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_BSS_MAX_STA[PATH_LEN];


extern char WID_DBUS_RADIO_METHOD_SET_SUPPORT_RATELIST[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_MAX_RATE[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_BSS_L3_POLICY[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_BSS_MAX_THROUGHPUT[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SHOW_BSS_MAX_THROUGHPUT[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SHOW_CHANNEL_CHANGE[PATH_LEN];

extern char WID_DBUS_RADIO_METHOD_RADIO_APPLY_WLANID_BASE_VLANID[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_RADIO_APPLY_WLANID_CLEAN_VLANID[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_RADIO_CPE_CHANNEL_APPLY_WLANID_BASE_VLANID[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_RADIO_CPE_CHANNEL_APPLY_WLANID_CLEAN_VLANID[PATH_LEN];

extern char WID_DBUS_RADIO_METHOD_RADIO_CHECK_RADIO_MEMBER[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_RADIO_APPLY_WLANID_BASE_NAS_PORT_ID[PATH_LEN];	//mahz add 2011.5.30
extern char WID_DBUS_RADIO_METHOD_RADIO_APPLY_WLANID_CLEAN_NAS_PORT_ID[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_RADIO_APPLY_WLANID_BASE_HOTSPOT_ID[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_RADIO_APPLY_WLANID_CLEAN_HOTSPOT_ID[PATH_LEN];

extern char WID_DBUS_RADIO_METHOD_SET_BSS_L3_IF_WLAN_BR[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SHOW_RADIO_QOS[PATH_LEN];



/* add for REQUIREMENTS-468 */
extern char	WID_DBUS_CONF_METHOD_ADD_DEL_MAC_GROUP[PATH_LEN];
extern char	WID_DBUS_CONF_METHOD_ADD_DEL_MAC_TOFROM_GROUP[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_MACGROUP[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOWMACGRP[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOWMACGRP_ALL[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_ELECTRONIC_MENU[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_MACGRP_SHOW_RUNNING_CONFIG_START[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_MACGRP_SHOW_RUNNING_CONFIG_END[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_VLANGRP_SHOW_RUNNING_CONFIG_START[PATH_LEN];
extern char	WID_DBUS_MACGRP_OBJPATH[PATH_LEN];
extern char WID_DBUS_MACGRP_INTERFACE[PATH_LEN];

extern char WID_DBUS_WTP_METHOD_BIND_MACGRP[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_UNBIND_MACGRP[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_ELECTRONIC_MENU[PATH_LEN];

extern char WID_DBUS_RADIO_METHOD_WLAN_BIND_MACGRP[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_WLAN_UNBIND_MACGRP[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_WLAN_ELECTRONIC_MENU[PATH_LEN];

extern char WID_DBUS_WLAN_METHOD_BIND_MACGRP[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_UNBIND_MACGRP[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_ELECTRONIC_MENU[PATH_LEN];

/*
arg lists for method WID_DBUS_CONF_METHOD_RADIO_APPLY_WLAN
 in arg list:
   	BYTE	Radio_G_ID//Global id of Radio
	BYTE	WlanID//id of wlan which radio apply
out arg list:  // in the order as they are appended in the dbus message.
	UNIT32	ret//success or fail(reason)
*/
extern char WID_DBUS_RADIO_METHOD_APPLY_WLAN[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_DELETE_WLAN[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_ENABLE_WLAN[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_DISABLE_WLAN[PATH_LEN];

extern char WID_DBUS_RADIO_METHOD_WDS_WLAN_SET[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SHOW_WDS_BSSID_INFO[PATH_LEN];

extern char WID_DBUS_RADIO_METHOD_REVOVER_DEFAULT_CONFIG[PATH_LEN];

extern char WID_DBUS_RADIO_METHOD_SET_MAX_THROUGHOUT[PATH_LEN];
extern char WID_DBUS_RADIO_WLAN_PACKET_POWER[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_RADIO_L2_ISOLATION_ABLE[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_11N_SET_RADIO_CWMMODE[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SHOW_BSS_LIST[PATH_LEN];

extern char WID_DBUS_RADIO_METHOD_SET_WTP_RADIO_AUTO_CHANNEL[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_WTP_RADIO_DIVERSITY[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_WTP_RADIO_TXANTENNA[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_WTP_RADIO_AUTO_CHANNEL_CONT[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_INTER_VAP_FORVARDING_ABLE[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_INTRA_VAP_FORVARDING_ABLE[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_KEEP_ALIVE_PERIOD[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_KEEP_ALIVE_IDLE_TIME[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_CONGESTION_AVOID_STATE[PATH_LEN];


extern char WID_DBUS_RADIO_METHOD_WLAN_TRAFFIC_LIMIT_ABLE[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_WLAN_TRAFFIC_LIMIT_VALUE[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_WLAN_TRAFFIC_LIMIT_AVERAGE_VALUE[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_WLAN_TRAFFIC_LIMIT_STA_VALUE[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_WLAN_TRAFFIC_LIMIT_CANCEL_STA_VALUE[PATH_LEN];

extern char WID_DBUS_RADIO_METHOD_WLAN_TRAFFIC_LIMIT_SEND_VALUE[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_WLAN_TRAFFIC_LIMIT_AVERAGE_SEND_VALUE[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_WLAN_TRAFFIC_LIMIT_STA_SEND_VALUE[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_WLAN_TRAFFIC_LIMIT_CANCEL_STA_SEND_VALUE[PATH_LEN];

/* radio apply wlan alias ESSID */
extern char WID_DBUS_RADIO_METHOD_RADIO_APPLY_WLANID_BASE_VLANID_ALIAS_ESSID[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_RADIO_APPLY_WLANID_CLEAN_ALIAS_ESSID[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_APPLY_WLAN_ALIAS_ESSID[PATH_LEN];


extern char WID_DBUS_RADIO_METHOD_SET_SA_ENABLE[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_SPECTRUM_ANALYSIS_LIST[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SPECTRUM_ANALYSIS[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SHOW_SPECTRUM_ANALYSIS[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SHOW_SPECTRUM_ANALYSIS_LIST[PATH_LEN];

extern char	WID_DBUS_QOS_OBJPATH[PATH_LEN];
extern char WID_DBUS_QOS_INTERFACE[PATH_LEN];

extern char WID_DBUS_QOS_METHOD_ADD_DEL_QOS[PATH_LEN];

extern char WID_DBUS_QOS_METHOD_SHOW_QOS_LIST[PATH_LEN];
extern char WID_DBUS_QOS_METHOD_SHOW_QOS[PATH_LEN];
extern char WID_DBUS_QOS_METHOD_CONFIG_QOS[PATH_LEN];

extern char WID_DBUS_QOS_METHOD_SET_QOS_INFO[PATH_LEN];
extern char WID_DBUS_QOS_METHOD_SET_QOS_INFO_CLIENT[PATH_LEN];
extern char WID_DBUS_QOS_METHOD_SET_QOS_MAP[PATH_LEN];
extern char WID_DBUS_QOS_METHOD_SET_QOS_WMM_MAP_DOT1P[PATH_LEN];
extern char WID_DBUS_QOS_METHOD_SET_QOS_DOT1P_MAP_WMM[PATH_LEN];

extern char WID_DBUS_RADIO_METHOD_APPLY_QOS[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_DELETE_QOS[PATH_LEN];
/*set wireless qos info for mib*/
extern char WID_DBUS_QOS_METHOD_SET_QOS_TOTAL_BANDWIDTH[PATH_LEN];
extern char WID_DBUS_QOS_METHOD_SHOW_QOS_EXTENSION_INFO[PATH_LEN];
extern char WID_DBUS_QOS_METHOD_SET_QOS_FLOW_PARAMETER[PATH_LEN];
extern char WID_DBUS_QOS_METHOD_SET_QOS_PARAMETER[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_DELETE_RADIO_WITH_QOS_PROFILE[PATH_LEN];   //fengwenchao add 20110427
extern char WID_DBUS_QOS_METHOD_SET_QOS_POLICY[PATH_LEN];
extern char WID_DBUS_QOS_METHOD_SET_QOS_POLICY_NAME[PATH_LEN];
extern char WID_DBUS_QOS_METHOD_SET_QOS_MANAGE_ARITHMETIC_NAME[PATH_LEN];
extern char WID_DBUS_QOS_METHOD_SHOW_RADIO_QOS_INFO[PATH_LEN];

/*ethereal bridge infomation area*/
extern char	WID_DBUS_EBR_OBJPATH[PATH_LEN];
extern char WID_DBUS_EBR_INTERFACE[PATH_LEN];

extern char WID_DBUS_EBR_METHOD_ADD_DEL_EBR[PATH_LEN];
extern char WID_DBUS_EBR_METHOD_SHOW_EBR_LIST[PATH_LEN];
extern char WID_DBUS_EBR_METHOD_SHOW_EBR[PATH_LEN];
extern char WID_DBUS_EBR_METHOD_CONFIG_EBR[PATH_LEN];
extern char WID_DBUS_EBR_METHOD_CONFIG_EBR_ENABLE[PATH_LEN];

extern char WID_DBUS_EBR_METHOD_SET_BRIDGE_ISOLATION[PATH_LEN];
extern char WID_DBUS_EBR_METHOD_SET_BRIDGE_MULTICAST_ISOLATION[PATH_LEN];

extern char WID_DBUS_EBR_METHOD_SET_BRIDGE_UCAST_SOLICT[PATH_LEN];			/* Huang Leilei add, 2012-11-12 11:24 */
extern char WID_DBUS_EBR_METHOD_SET_BRIDGE_MCAST_SOLICT[PATH_LEN];			/* Huang Leilei add, 2012-11-12 20:09 */

extern char WID_DBUS_EBR_METHOD_SET_EBR_ADD_DEL_IF[PATH_LEN];
extern char WID_DBUS_EBR_METHOD_SET_BRIDGE_SAMEPORTSWITCH[PATH_LEN];
extern char WID_DBUS_EBR_METHOD_EBR_INTERFACE_EBR[PATH_LEN];
extern char WID_DBUS_EBR_METHOD_SET_MULTICAST_FDB_LEARN[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_EBR_SHOW_RUNNING_CONFIG_START[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_EBR_SHOW_RUNNING_CONFIG_END[PATH_LEN];

/*
Wid config infomation 
*/

extern char WID_DBUS_CONF_METHOD_ADD_OUI[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_ADD_ESSID[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_ADD_ATTACK_MAC[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_DEL_OUI[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_DEL_ESSID[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_DEL_ATTACK_MAC[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_OUI_SHOW[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_ESSID_SHOW[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_ATTACK_MAC_SHOW[PATH_LEN];




extern char WID_DBUS_CONF_METHOD_WIDCONFIG[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_LEV3_PROTOCOL[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SECURITY_TYPE[PATH_LEN];	
extern char WID_DBUS_CONF_METHOD_HW_VERSION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SW_VERSION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AC_NAME[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_MAX_WTP[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_MAX_MTU[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_LOG_SWITCH[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_LOG_SIZE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_LOG_LEVEL[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_DAEMONLOG_DEBUG_OPEN[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_AP_SCANNING[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_SCANNING_REPORT_INTERVAL[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_UPDATE_AP_SCANNING_INFO[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WHITELIST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_BLACKLIST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WHITELIST_DELETE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_BLACKLIST_DELETE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_ROGUE_AP_LIST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_ROGUE_AP_THRESHOLD[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_ROGUE_AP_LIST_V1[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_ROGUE_AP_LIST_BYWTPID[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_DYNAMIC_CHANNEL_SELECTION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_DYNAMIC_CHANNEL_SELECTION_RANGE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_NEIGHBOR_AP_LIST_BYWTPID[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_NEIGHBOR_AP_LIST[PATH_LEN];   //fengwenchao add 20101220
extern char WID_DBUS_CONF_METHOD_NEIGHBOR_AP_LIST_BYWTPID2[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WHITELIST_SHOW[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_BLACKLIST_SHOW[PATH_LEN];
/*country code area*/
extern char WID_DBUS_CONF_METHOD_SET_COUNTRY_CODE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_UNDO_COUNTRY_CODE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_COUNTRY_CODE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_TRANSMIT_POWER_CONTROL[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_TXPOWER_THRESHOLD[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_ROGUE_AP_TRAP_THRESHOLD[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_COVERAGE_THRESHOLD[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_NEIGHBOR_RSSI_INFO[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_CONTROL_SCOPE[PATH_LEN];
/*auto ap area*/
extern char WID_DBUS_CONF_METHOD_SET_WID_DYNAMIC_AP_LOGIN_SWITCH[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WID_DYNAMIC_AP_LOGIN_L3_INTERFACE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WID_LISTEN_L3_INTERFACE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WID_LISTEN_IP[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_WID_LISTEN_L3_INTERFACE[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_SET_WID_DYNAMIC_AP_LOGIN_WLANID[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_DEL_WID_DYNAMIC_AP_LOGIN_WLANID[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WID_DYNAMIC_AP_LOGIN_SAVE_CONFIG_SWITCH[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_WID_DYNAMIC_AP_LOGIN_SAVE_CONFIG[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_CLEAR_WID_DYNAMIC_AP_LOGIN_CONFIG[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_DATA_EXCLUDE_MULTICAST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_STATISTICS[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_STATISTICS_INTERVAL[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_TIMESTAMP[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_SHOW_STATISTICS_LIST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_SHOW_IPADDR[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WID_AP_IP_GATEWAY_DNS[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_SHOW_NETWORK[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AC_LOAD_BALANCE[PATH_LEN];
extern char WID_DBUS_CONF_AC_LOAD_BALANCE_PARA[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_INTERFACE_ETH_MTU[PATH_LEN];  //fengwenchao add 20110126



extern char WID_DBUS_CONF_METHOD_SET_WID_AC_EXTENTION_INFOR_ENABLE[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_SET_WID_AP_MAX_THROUGHOUT[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_SET_WID_AP_EXTENSION_COMMAND[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WID_AP_OPTION60_PARAMETER[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_SET_WID_AP_IP_GATEWAY[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_TCPDUMP_AP_EXTENSION_COMMAND[PATH_LEN];

/*mib area*/
extern char WID_TRAP_OBJPATH[PATH_LEN];
extern char WID_TRAP_INTERFACE[PATH_LEN];

extern char WID_DBUS_TRAP_WID_WTP_ENTER_IMAGEDATA_STATE[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_CHANNEL_CHANGE[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WLAN_ENCRYPTION_TYPE_CHANGE[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WLAN_PRESHARED_KEY_CHANGE[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_TRANFER_FILE[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_UPDATE_SUCCESSFUL[PATH_LEN];   /*fengwenchao add 20110216*/
extern char WID_DBUS_TRAP_WID_WTP_UPDATE_FAIL[PATH_LEN];   /*fengwenchao add 20110216*/

extern char WID_DBUS_TRAP_WID_WTP_CODE_START[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_ELECTRIFY_REGISTER_CIRCLE[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_AP_DOWN[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_AP_REBOOT[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_IP_CHANGE_ALARM[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_ACTIMESYNCHROFAILURE[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_DEVICE_INTERFERENCE_DETECTED[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_SHOW_RUNTIME[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_REMOTE_RESTART[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_DIVORCE_NETWORK[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_AP_FLASH_WRITE_FAIL[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_SHOW_WID_WTP_RUNTIME[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WID_WTP_LOCATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_WID_WTP_LOCATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WID_WTP_NETID[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_WID_WTP_NETID[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WID_MONITOR_TIME[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WID_SAMPLE_TIME[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_WID_SAMPLE_INFO[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WID_MONITOR_ENABLE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WID_SAMPLE_ENABLE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WID_IPFWD[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_WID_IPFWD[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_SET_AP_UPDATE_TIMER[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_AP_UPDATE_TIMER[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_SET_AP_L2_ISOLATION_ABLE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_AP_PREVENT_DOS_ATTACK[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_AP_IGMP_SNOOPING[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_AP_MIB_INFO[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_SET_AP_CM_THRESHOLD[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_AP_CM_THRESHOLD[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_AP_CM_STATISTICS[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_AC_BALANCE_CONFIGURATION[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_AP_CHANNEL_DISTURB_TRAP[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_SHOW_MODEL_INFOMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_SHOW_MODEL_CODE_INFOMATION[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_AP_SHOW_WTP_EXTENSION_INFOMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_SHOW_WTP_EXTENSION_INFOMATION_V2[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_SHOW_WTP_EXTENSION_INFOMATION_V3[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_SHOW_WTP_EXTENSION_INFOMATION_V4[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_AP_SHOW_WTP_MAX_POWER[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_SHOW_RRM_CONFIG[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_SHOW_WTP_TXPOWER_CONTROL[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_RECEIVER_SIGNAL_LEVEL[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_RECEIVER_SIGNAL_LEVEL[PATH_LEN];

extern char WID_DBUS_TRAP_WID_WTP_CHANNEL_DEVICE_INTERFERENCE[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_CHANNEL_AP_INTERFERENCE[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_NEIGHBOR_CHANNEL_AP_INTERFERENCE[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_CHANNEL_TERMINAL_INTERFERENCE[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_CHANNEL_COUNT_MINOR[PATH_LEN];

extern char WID_DBUS_TRAP_WID_WTP_AC_DISCOVERY_DANGER_AP[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_AC_DISCOVERY_COVER_HOLE[PATH_LEN];

extern char WID_DBUS_TRAP_WID_AP_CPU_THRESHOLD[PATH_LEN];
extern char WID_DBUS_TRAP_WID_AP_MEM_THRESHOLD[PATH_LEN];
extern char WID_DBUS_TRAP_WID_AP_TEMP_THRESHOLD[PATH_LEN];
extern char WID_DBUS_TRAP_WID_AP_ROGUE_THRESHOLD[PATH_LEN];
extern char WID_DBUS_TRAP_WID_AP_WIFI_IF_ERROR[PATH_LEN];
extern char WID_DBUS_TRAP_WID_AP_ATH_ERROR[PATH_LEN];
extern char WID_DBUS_TRAP_WID_AP_RRM_STATE_CHANGE[PATH_LEN];
extern char WID_DBUS_TRAP_WID_AP_RUN_QUIT[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_SHOW_WID_WTP_SAMPLE_THROUGHPUT_INFO[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_WID_WTP_WLAN_VLAN_INFO[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_WID_WTP_ETH_IF_INFO[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WID_WATCH_DOG[PATH_LEN];

/* add for sample  begin*/
extern char WID_DBUS_WTP_METHOD_SET_WTP_MOMENT_INFOMATION_SWITCH[PATH_LEN];     
extern char WID_DBUS_WTP_METHOD_SET_WTP_MOMENT_INFOMATION_REPORTINTERVAL[PATH_LEN];      
extern char WID_DBUS_WTP_METHOD_SET_WTP_SAMPLE_INFOMATION_REPORTINTERVAL[PATH_LEN];	
extern char WID_DBUS_WTP_METHOD_SHOW_WTP_ROUTINE_INFOMATION_REPORTINTERVAL[PATH_LEN];		
extern char WID_DBUS_WTP_METHOD_SHOW_WTP_MOMENT_INFOMATION_REPORTINTERVAL[PATH_LEN];		
/* add for sample  end*/

/*******************************************for mib optimize begin**********************************************/
/*add by nl for showing wtp information for mib need 20100507*/
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_BASIC_INFORMATION[PATH_LEN];	
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_COLLECT_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_PARA_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_WIRELESS_IFSTATS_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_DEVICE_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_DATA_PKTS_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_STATS_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WLAN_STATS_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WLAN_SSID_STATS_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_INFORMATION[PATH_LEN];    /*fengwenchao add 20110617*/
extern char WID_DBUS_CONF_METHOD_SHOW_INFO_BYWLANID[PATH_LEN];    /*fengwenchao add 20110617*/
extern char WD_DBUS_CONF_METHOD_SHOW_INFO_ALLWLAN[PATH_LEN];  /*fengwenchao add 20110617*/
extern char WID_DBUS_CONF_METHOD_SHOW_INFO_BYWTPID[PATH_LEN];   /*fengwenchao add 20110617*/
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_IFNAME_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_RADIO_PARA_INFOR_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_ETH_PORT_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_RADIO_STATS_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_RADIO_CONFIG_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_WIRED_STATS_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_WIRELESS_STATS_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_NEW_WTPWIRELESS_IF_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_NEW_WTP_WIRELESS_IFSTATS_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_ROGUE_WTP_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_HIDE_QUIT_WTP_INFOR_IN_MIB_SHOWING[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_NETWORK_INFO[PATH_LEN];/*xdw add for show ap network information of all wtp, 20101215*/
/* zhangshu add 2010-08-30 */
extern char WID_DBUS_CONF_METHOD_SET_WTP_TRAP_IGNORE_PERCENT[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_HIDE_QUIT_WTP_INFOR_IN_MIB_SHOWING[PATH_LEN];

//mahz add 2011.1.21
extern char WID_DBUS_CONF_METHOD_SHOW_RADIO_INFO_BYWTPID_WID[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_BSS_ADD_MAC_LIST[PATH_LEN];		//mahz add 2011.5.12
extern char WID_DBUS_CONF_METHOD_BSS_DEL_MAC_LIST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_BSS_USE_MAC_LIST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_BSS_MAC_LIST[PATH_LEN];

/*fengwenchao add 20110329*/
extern char WID_DBUS_CONF_METHOD_SHOW_STATISTICS_INFOMATION_OF_ALL_WTP_WHOLE[PATH_LEN];

/*luzhenhua append  2010-05-26 */
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_WLAN_DATA_PKTS_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_ATH_STATISTICS_INFOMATION[PATH_LEN];		
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WLAN_SSID_CONFIG_INFORMATION[PATH_LEN]; 
extern char WID_DBUS_STA_METHOD_SHOW_TERMINAL_INFO_OF_ALL_WTP[PATH_LEN];

/*****************************************for mib optimize end**********************************************/

/*
extern char ASD_DBUS_SIG_STA_LEAVE	"signal_sta_leave"



extern char ASD_DBUS_SIG_STA_COME   "signal_sta_come"
extern char ASD_DBUS_SIG_WTP_DENY_STA   "signal_wtp_deny"
extern char ASD_DBUS_SIG_DE_WTP_DENY_STA   "signal_de_wtp_deny"


extern char ASD_DBUS_SIG_STA_VERIFY	"signal_sta_verify"
extern char ASD_DBUS_SIG_STA_VERIFY_FAILED   "signal_sta_verify_failed"


extern char ASD_DBUS_SIG_STA_ASSOC_FAILED   "signal_sta_assoc_failed"
extern char ASD_DBUS_SIG_STA_JIANQUAN_FAILED   "signal_sta_jianquan_failed"
*/

extern char WID_DBUS_TRAP_WID_WTP_WIRELESS_INTERFACE_DOWN[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_WIRELESS_INTERFACE_DOWN_CLEAR[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_CONFIG_CHANGE[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_SET_MODEL[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_MODEL[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_MODEL_LIST[PATH_LEN];


extern char WID_DBUS_TRAP_WID_WTP_AC_DISCOVERY_COVER_HOLE_CLEAR[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_CHANNEL_DEVICE_INTERFERENCE_CLEAR[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_CHANNEL_AP_INTERFERENCE_CLEAR[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_CHANNEL_TERMINAL_INTERFERENCE_CLEAR[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_CHANNEL_COUNT_MINOR_CLEAR[PATH_LEN];

extern char WID_DBUS_TRAP_WID_WTP_FIND_UNSAFE_ESSID[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_FIND_WIDS_ATTACK[PATH_LEN];		
extern char WID_DBUS_TRAP_WID_SSID_KEY_CONFLICT[PATH_LEN];		

extern char WID_DBUS_CONF_METHOD_SHOW_WIDS_STATISTICS_LIST_BYWTPID[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_WIDS_STATISTICS_LIST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_CLEAR_WIDS_STATISTICS_LIST_BYWTPID[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_CLEAR_WIDS_STATISTICS_LIST[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_SHOW_WIDS_DEVICE_LIST_BYWTPID[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_WIDS_DEVICE_LIST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_WIDS_DEVICE_OF_ALL[PATH_LEN];   //fengwenchao add 20101227
extern char WID_DBUS_CONF_METHOD_CLEAR_WIDS_DEVICE_LIST_BYWTPID[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_CLEAR_WIDS_DEVICE_LIST[PATH_LEN];
extern char WID_BAK_OBJPATH[PATH_LEN];
extern char WID_BAK_INTERFACE[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_MASTER_BAK_SET[PATH_LEN];
extern char WID_DBUS_AC_METHOD_UPDATE_BAK_INFO[PATH_LEN];
extern char WID_DBUS_AC_METHOD_SYNCHRONIZE_INFO[PATH_LEN];
extern char WID_DBUS_AC_METHOD_ASD_SYNCHRONIZE_INFO[PATH_LEN];
extern char WID_DBUS_AC_METHOD_NOTICE_INFO[PATH_LEN];
extern char WID_DBUS_AC_METHOD_VRRP_INFO[PATH_LEN];
extern char WID_DBUS_AC_METHOD_VRRP_SOCK_INFO[PATH_LEN];

extern char WID_DBUS_WLAN_METHOD_FORMARD_MODE[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_TUNNEL_MODE[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_SET_NEIGHBORDEAD_INTERVAL[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_NEIGHBORDEAD_INTERVAL[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_WTPLIST_BYWLANID[PATH_LEN];

extern char WID_DBUS_WTP_METHOD_SET_UPDATE_PATH[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_UPDATE_CONFIG[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_CLEAR_UPDATE_CONFIG[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_TRAP_DEBUG_OPEN[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_TRAP_SWITCH_ABLE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_TRAP_SWITCH_SHOW[PATH_LEN];
extern char	WID_DBUS_WTP_METHOD_UPDATE_WTP_IMG[PATH_LEN];
extern char	WID_DBUS_WTP_METHOD_CLEAR_UPDATE_WTP_IMG[PATH_LEN];
extern char	WID_DBUS_WTP_METHOD_UPDATE_WTP_IMG_LIST[PATH_LEN];
extern char	WID_DBUS_WTP_METHOD_CLEAR_UPDATE_WTP_IMG_LIST[PATH_LEN];
/*mahz add for ap upgrade automatically*/
extern char WID_DBUS_WTP_METHOD_BIND_MODEL_WITH_FILE[PATH_LEN];	
extern char WID_DBUS_WTP_METHOD_SET_AP_UPDATE_BASE_MODEL[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SHOW_MODEL_BIND_INFO[PATH_LEN];	
extern char WID_DBUS_WTP_METHOD_DELETE_MODEL_BIND_INFO[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_CLEAR_ONE_MODEL_UPDATE_CONFIG[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SHOW_DETAIL_MODEL_BIND_INFO[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_AP_UPDATE_COUNT_ONETIME[PATH_LEN];	
extern char WID_DBUS_WTP_METHOD_SET_AP_UPDATE_CONTROL[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SHOW_AP_UPGRADE_RESULT_INFO[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_UPDATE_WTPCOMPATIBLE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_AP_UPDATE_FAIL_COUNT[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_AP_UPDATE_FAIL_COUNT[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WTPLIST_UPDATE_FAIL_LIST[PATH_LEN];
extern char	WID_DBUS_WTP_METHOD_CLEAR_UPDATE_FAIL_WTP_LIST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_OLD_AP_IMG[PATH_LEN];

/*zhanglei add for bak ac ip list group*/
extern char	WID_DBUS_ACIPLIST_OBJPATH[PATH_LEN];
extern char WID_DBUS_ACIPLIST_INTERFACE[PATH_LEN];
extern char	WID_DBUS_ACIPLIST_METHOD_CONFIG[PATH_LEN];
extern char	WID_DBUS_ACIPLIST_METHOD_ADD_AC_IP_LIST_GROUP[PATH_LEN];
extern char	WID_DBUS_ACIPLIST_METHOD_DEL_AC_IP_LIST_GROUP[PATH_LEN];
extern char	WID_DBUS_ACIPLIST_METHOD_CONFIG_AC_IP_LIST[PATH_LEN];
extern char	WID_DBUS_ACIPLIST_METHOD_ADD_AC_IP[PATH_LEN];
extern char	WID_DBUS_ACIPLIST_METHOD_DEL_AC_IP[PATH_LEN];
extern char	WID_DBUS_ACIPLIST_METHOD_SET_AC_IP_PRIORITY[PATH_LEN];
extern char	WID_DBUS_ACIPLIST_METHOD_AC_IP_LIST_GROUP_SWITCH[PATH_LEN];
extern char WID_DBUS_ACIPLIST_METHOD_SHOW_AC_IP_LIST[PATH_LEN];
extern char WID_DBUS_ACIPLIST_METHOD_SHOW_AC_IP_LIST_ONE[PATH_LEN];
extern char WID_DBUS_ACIPLIST_METHOD_SHOW_RUNNING_CONFIG[PATH_LEN];

extern char WID_DBUS_RADIO_METHOD_WLAN_SET_STA_IP_MAC_BINDING[PATH_LEN];

extern char WID_DBUS_WLAN_METHOD_APPAY_WLAN_IFNAME_IPV6[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_APPAY_WTP_IFNAME_IPV6[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_WLAN_SET_STA_VLANID[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_WLAN_SET_STA_DHCP_BEFORE_AUTHERIZED[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_HOTREBOOT[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_ACCESS_THROUGH_NAT[PATH_LEN];

extern char WID_DBUS_WTP_METHOD_SET_WTP_WIDS_POLICY[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_ADD_WID_MAC[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_DEL_WID_MAC[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WIDS_MAC_SHOW[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_COUNTERMEASURES[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_COUNTERMEASURES_MODE[PATH_LEN];

extern char  WID_DBUS_RADIO_METHOD_SET_ACKTIMEOUT_DISTANCE[PATH_LEN];/*wcl add for RDIR-33*/
extern char  WID_DBUS_RADIO_METHOD_SET_GUARD_INTERVAL[PATH_LEN];
extern char  WID_DBUS_RADIO_METHOD_SET_MCS[PATH_LEN];
extern char  WID_DBUS_RADIO_METHOD_SET_CMMODE[PATH_LEN];

extern char WID_DBUS_EBR_METHOD_SET_EBR_ADD_DEL_UPLINK[PATH_LEN];
extern char WID_DBUS_EBR_METHOD_SHOW_FDB_SUMMARY_DETAIL[PATH_LEN];

extern char  WID_DBUS_RADIO_METHOD_SET_WDS_DISTANCE[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_WDS_REMOTE_BRMAC[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_WDS_WEP_KEY[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_WDS_AES_KEY[PATH_LEN];
extern char  WID_DBUS_RADIO_METHOD_SET_WDS_ENCRYPTION_TYPE[PATH_LEN];
extern char  WID_DBUS_RADIO_SECTOR_SET_CMD[PATH_LEN];
extern char  WID_DBUS_RADIO_TX_CHAINMASK_SET_CMD[PATH_LEN];
extern char  WID_DBUS_RADIO_TX_CHAINMASK_SET_CMD_V2	[PATH_LEN];

extern char  WID_DBUS_RADIO_SECTOR_POWER_SET_CMD[PATH_LEN];
extern char  WID_DBUS_RADIO_NETGEAR_G_SET_CMD[PATH_LEN];

extern char  WID_DBUS_WTP_LIST_METHOD_SET_DHCP_SNOOPING[PATH_LEN];
extern char  WID_DBUS_WTP_METHOD_SET_DHCP_SNOOPING[PATH_LEN];
extern char  WID_DBUS_WTP_LIST_METHOD_STA_INFO_REPORT[PATH_LEN];
extern char  WID_DBUS_WTP_METHOD_STA_INFO_REPORT[PATH_LEN];
extern char  WID_DBUS_WLAN_METHOD_STA_IP_MAC_BINDING[PATH_LEN];
extern char  WID_DBUS_WLAN_WTP_LIST_METHOD_STA_STATIC_ARP[PATH_LEN];
extern char  WID_DBUS_WLAN_WTP_METHOD_STA_STATIC_ARP[PATH_LEN];

extern char WID_DBUS_WLAN_METHOD_SERVICE_CONTROL_TIMER[PATH_LEN];
extern char  WID_DBUS_WLAN_METHOD_TIMER_ABLE[PATH_LEN];
extern char  WID_DBUS_CONF_METHOD_SHOW_AP_TRAP_ROGUE_AP_TERMINAL_CPU_MEM_THRESHOLD[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WTP_ROGUEAP_ROGUETERMINAL_CPU_MEM_TRAP_THRESHOLD[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WTP_TRAP_SWITCH[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WTP_SEQNUM_SWITCH[PATH_LEN]; /*wcl add*/
extern char WID_DBUS_CONF_METHD_SET_WID_ROGUE_DANGER_UNSAFE_ATTACK_TRAP_STATE[PATH_LEN];   /*fengwenchao add 20110221*/
extern char WID_DBUS_CONF_METHOD_MODIFY_ESSID[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_AMPDU_ABLE[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_AMPDU_LIMIT[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_AMPDU_SUBFRAME[PATH_LEN]; // zhangshu add for subframe , 2010-10-09

extern char WID_DBUS_RADIO_METHOD_SET_MIXED_PURE_N[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_STA_WAPI_INFO_SWITCH[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_STA_WAPI_INFO_REPORTINTERVAL[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_CHANNEL_OFFSET[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_TXPOWER_STEP[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_RADIO_WLAN_LIMIT_RSSI_ACCESS_STA[PATH_LEN]; //fengwenchao add 20120222 for RDIR-25
extern char WID_DBUS_ACIPLIST_METHOD_SET_AC_IP_BANLANCE_FLAG[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_MAC_WHITELIST_SWITCH[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_ESSID_WHITELIST_SWITCH[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_CHANGE_WHITELIST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_CHANGE_BLACKLIST [PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_TPC_POLICY[PATH_LEN];
extern char WID_DBUS_ACIPLIST_METHOD_SET_AC_IP_THRESHOLD[PATH_LEN];
extern char WID_DBUS_ACIPLIST_METHOD_SET_AC_IP_DIFF_BANLANCE[PATH_LEN];


extern char  WID_DBUS_RADIO_METHOD_TIMER_ABLE[PATH_LEN];
extern char  WID_DBUS_RADIO_METHOD_SERVICE_CONTROL_TIMER[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_WIDS_MONITOR_MODE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WIDS_SCANNING_MODE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WIDS_SCANNING_CHANNEL[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WIDS_SCANNING_MODE_CHANNEL_SHOW[PATH_LEN];
extern char WID_DBUS_AC_METHOD_SET_INTERFACE_VMAC[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WID_AP_IP_MODE[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_INTERFACE_ETH_MTU[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_ACCESS_WTP_VENDOR_COUNT_SHOW[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WIDS_JUDGE_POLICY[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WIDS_JUDGE_POLICY_SHOW[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_TUNNEL_MODE_POLICY[PATH_LEN];
extern char  WID_DBUS_RADIO_METHOD_SET_AMPDU_SUBFREAM[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_MIMO[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_LICENSE_BINDING[PATH_LEN];		/*xiaodawei append, 20101029*/
extern char WID_DBUS_IPERF_WTPIP[PATH_LEN];							//xiaodawei add, 20110303
extern char WID_DBUS_CONF_METHOD_SET_WTP_LINK_DETECT[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WSM_SWITCH[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_VLAN_SWITCH[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_DHCP_OPTION82_SWITCH[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_NEIGHBOR_SAME_CHANNELRSSI_THRESHOLD[PATH_LEN];/*zhaoruijia,tranlate  neighbor_channel_interference to 1.3*/

extern char WID_DBUS_AP_GROUP_OBJPATH[PATH_LEN];
extern char WID_DBUS_AP_GROUP_INTERFACE[PATH_LEN];
extern char WID_DBUS_AP_GROUP_METHOD_CONFIG[PATH_LEN];
extern char WID_DBUS_AP_GROUP_METHOD_CREATE[PATH_LEN];
extern char WID_DBUS_AP_GROUP_METHOD_DEL[PATH_LEN];
extern char WID_DBUS_AP_GROUP_METHOD_ADD_DEL_MEMBER[PATH_LEN];
extern char WID_DBUS_AP_GROUP_METHOD_SHOW_MEMBER[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SERVICE_TFTP_SWITCH[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_SERVICE_TFTP_SWITCH[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SERVICE_FTP_SWITCH[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_SERVICE_FTP_SWITCH[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_SHOW_WLAN_RADIO_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WID_ERROR_HANDLE_STATE[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_SET_WLAN_STA_TUNNEL_SWITCH_STATE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WLAN_STA_STATE[PATH_LEN];

extern char WID_DBUS_WTP_METHOD_SHOW_WTP_RADIO_PKT_INFO_TUNNEL[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_SHOW_WLAN_PTK_INFO[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_RADIO_RX_DATA_DEAD_TIME[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_RADIO_RX_DATA_DEAD_TIME_SHOW[PATH_LEN];
extern char WID_DBUS_QOS_METHOD_SET_QOS_FLOW_PARAMETER_V2[PATH_LEN];
extern char WID_DBUS_QOS_METHOD_SET_QOS_FLOW_ABLE[PATH_LEN];
extern char WID_DBUS_QOS_METHOD_SET_QOS_FLOW_ABLE_V2[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WTP_COLLECT_TIME[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_DBUS_COUNT[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_DBUS_COUNT[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_ADD_BLACK_WHITE_OUI_MAC[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_DEL_BLACK_WHITE_OUI_MAC[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_BLACK_WHITE_OUI_INFO[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_UPDATE_BLACK_WHITE_OUI_INFO_LIST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_USE_BLACK_WHITE_NONE_OUI_POLICY[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_OUI_POLICY[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_CONFLICT_WTP_LIST[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_CHECKING[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_QUIT[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_LOCAL_HASNI_STATE_CHANGE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WIDS_MONITOR_MODE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WIDS_SCANNING_MODE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WIDS_SCANNING_CHANNEL[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WIDS_SCANNING_MODE_CHANNEL_SHOW[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_MULTICAST_LISTEN_SETTING[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_NO_RESPONSE_TO_STA_PROBLE_REQUEST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_UNI_MUTI_BR_CAST_ISOLATION_SW_AND_RATE_SET[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_MUTI_BR_CAST_RATE_SET[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WLAN_NO_RESPONSE_TO_STA_PROBLE_REQUEST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WLAN_UNI_MUTI_BR_CAST_ISOLATION_SW_AND_RATE_SET[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WLAN_MUTI_BR_CAST_RATE_SET[PATH_LEN];

extern char WID_DBUS_WLAN_METHOD_TUNNEL_NODE_SETTING[PATH_LEN];

/* REQUIREMENTS-536/ENR4-2 for 5G-FIRST */
extern char WID_DBUS_WTP_METHOD_5G_FIRST_SWITCH[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_5G_FIRST_DISCARD_COUNT[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_5G_FIRST_SCANTIME_THR[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_5G_FIRST_AGINGTIME_THR[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_5G_FIRST_STACOUNT_THR[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_5G_FIRST_SIGNAL_STRENGTH_THR[PATH_LEN];

/*ENR-17-BEGIN*/
extern char WID_DBUS_WLAN_METHOD_CTR_LIST_ENABLE[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_CTR_LIST_TIME[PATH_LEN];
/*ENR-17-END*/

/*station acl group */
extern char WID_DBUS_CONF_METHOD_ACLGRP_CREATE_ACL_RULE_TCPUDP[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_ACLGRP_CREATE_ACL_RULE_ICMP[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_ACLGRP_CREATE_ACL_RULE_DOMAIN[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_ACLGRP_DEL_ACL_RULE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_ACLGRP_SHOW_ACL_RULE_ID[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_ACLGRP_SHOW_ACL_RULE_ALL[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_ACLGRP_ADD_DEL_ACL_GROUP[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_ACLGRP_CONFIG_ACL_GROUP[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_ACLGRP_SHOW_ACL_GROUP[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_ACLGRP_SHOW_ACL_GROUP_ALL[PATH_LEN];

extern char WID_DBUS_ACLGRP_METHOD_ACLGRP_ADD_DEL_ACL_RULE_INGROUP[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_ACLGRP_SHOW_RUNNING_CONFIG_START[PATH_LEN];

extern char WID_DBUS_WLAN_METHOD_BIND_UNBIND_ACLGRP[PATH_LEN];
extern char	WID_DBUS_ACLGRP_OBJPATH[PATH_LEN];
extern char WID_DBUS_ACLGRP_INTERFACE[PATH_LEN];

/* add for dynamic vlan */
extern char WID_DBUS_WLAN_METHOD_SET_DYNAMIC_VLAN_ON_OFF[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_CHANGE_DYNAMIC_VLAN_LIST[PATH_LEN];
/* add for ENR4-3 */
extern char WID_DBUS_VLAN_GROUP_METHOD_CREATE_VLAN_GROUP[PATH_LEN];
extern char WID_DBUS_VLAN_GROUP_METHOD_DELETE_VLAN_GROUP[PATH_LEN];
extern char WID_DBUS_VLAN_GROUP_METHOD_CONFIG[PATH_LEN];
extern char WID_DBUS_VLAN_GROUP_METHOD_SET_WLAN_FOR_VLAN_GROUP[PATH_LEN];
extern char WID_DBUS_VLAN_GROUP_METHOD_ADD_DEL_VLAN_GROUP_MEMBER[PATH_LEN];
extern char WID_DBUS_VLAN_GROUP_METHOD_SET_VLAN_FOR_VLAN_GROUP[PATH_LEN];
extern char WID_DBUS_METHOD_SET_VLAN_GROUP_SERVICE_ENABLE_DISABLE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_VLAN_GROUP[PATH_LEN];
/*****************Qos mapping ***************************/

extern char WID_DBUS_WLAN_METHOD_QOS_AC_11E_TO_1P[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_QOS_AC_11E_TO_1P_DEFAULT[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_QOS_AC_DSCP_TO_1P[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_QOS_AC_DSCP_TO_1P_DEFAULT[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_QOS_AC_DSCP_TO_DSCP[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_QOS_AC_DSCP_TO_DSCP_DEFAULT[PATH_LEN];

extern char WID_DBUS_WLAN_METHOD_QOS_AP_11E_TO_1P[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_QOS_AP_11E_TO_1P_DEFAULT[PATH_LEN];

extern char WID_DBUS_WLAN_METHOD_QOS_AP_11E_TO_DSCP[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_QOS_AP_11E_TO_DSCP_DEFAULT[PATH_LEN];

extern char WID_DBUS_WLAN_METHOD_QOS_AP_DSCP_TO_11E[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_QOS_AP_DSCP_TO_11E_DEFAULT[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_QOS_AP_1P_TO_11E[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_QOS_AP_1P_TO_11E_DEFAULT[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_SHOW_QOS_MAP_INFO[PATH_LEN];

extern char WID_DBUS_WLAN_METHOD_SET_AP_11E_TO_1P_MAP_SWITCH[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_SET_AP_11E_TO_DSCP_MAP_SWITCH[PATH_LEN];

extern char WID_DBUS_WTP_METHOD_SET_WTP_COMMENT[PATH_LEN];

extern char WID_DBUS_ADD_USER_NETWORK[PATH_LEN];
extern char WID_DBUS_ADD_GUEST_NETWORK[PATH_LEN];
extern char WID_DBUS_ADD_NETWORK[PATH_LEN];
extern char WID_DBUS_DEL_NETWORK[PATH_LEN];
extern char WID_DBUS_MODIFY_NETWORK_CONFIG[PATH_LEN];
extern char WID_DBUS_LOAD_NETWORK_CONFIG[PATH_LEN];
extern char WID_DBUS_SHOW_NETWORK_CONFIG[PATH_LEN];
extern char WID_DBUS_SHOW_NETWORK_STA_CONFIG[PATH_LEN];
extern char WID_DBUS_SHOW_NETWORK_WTP_CONFIG[PATH_LEN];
extern char WID_DBUS_SHOW_NETWORK_WTP_IP_LIST[PATH_LEN];
extern char WID_DBUS_RESTART_WTP_BY_ID[PATH_LEN];

extern char	WID_DBUS_CONF_METHOD_ADD_WTP[PATH_LEN];
extern char	WID_DBUS_CONF_METHOD_DEL_WTP[PATH_LEN];
extern char	WID_DBUS_CONF_METHOD_LOAD_WTP[PATH_LEN];

extern char WID_DBUS_ADD_USER_GROUP[PATH_LEN];
extern char WID_DBUS_DEL_USER_GROUP[PATH_LEN];
extern char WID_DBUS_MODIFY_USER_GROUP_CONFIG[PATH_LEN];


/***************end Qos mappig **************************/
#endif
